// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvGGec13M9QEgoisfSIN3u04bIchoEuT0',
    appId: '1:284960503051:web:ebd2a5805f9ab62bdf1e0e',
    messagingSenderId: '284960503051',
    projectId: 'ytpro-cd31b',
    authDomain: 'ytpro-cd31b.firebaseapp.com',
    storageBucket: 'ytpro-cd31b.firebasestorage.app',
    measurementId: 'G-7D1XCKT4KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuTGRLn8W4TMeRQYWNoQPV-_REsWpgWrk',
    appId: '1:284960503051:android:4cf7828ca56d9954df1e0e',
    messagingSenderId: '284960503051',
    projectId: 'ytpro-cd31b',
    storageBucket: 'ytpro-cd31b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8IoJQXnkNrr8kq1O8Wmj2VbCUhcrjfFk',
    appId: '1:284960503051:ios:b2178024870ad70bdf1e0e',
    messagingSenderId: '284960503051',
    projectId: 'ytpro-cd31b',
    storageBucket: 'ytpro-cd31b.firebasestorage.app',
    iosClientId: '284960503051-17knffna0t5mrjp4u4fpf7sojh7jacrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.yt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8IoJQXnkNrr8kq1O8Wmj2VbCUhcrjfFk',
    appId: '1:284960503051:ios:b2178024870ad70bdf1e0e',
    messagingSenderId: '284960503051',
    projectId: 'ytpro-cd31b',
    storageBucket: 'ytpro-cd31b.firebasestorage.app',
    iosClientId: '284960503051-17knffna0t5mrjp4u4fpf7sojh7jacrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.yt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvGGec13M9QEgoisfSIN3u04bIchoEuT0',
    appId: '1:284960503051:web:bde19f531995a3eadf1e0e',
    messagingSenderId: '284960503051',
    projectId: 'ytpro-cd31b',
    authDomain: 'ytpro-cd31b.firebaseapp.com',
    storageBucket: 'ytpro-cd31b.firebasestorage.app',
    measurementId: 'G-56MKMVHJSC',
  );
}
